import { CMSAdapter, Article, Category, Author } from "../interface";

const mockAuthors: Author[] = [
    {
        id: "1",
        name: "Jordan Martinez",
        slug: "jordan-martinez",
        avatar: "https://i.pravatar.cc/150?u=jordan",
        bio: "Former broke millennial turned personal finance enthusiast. I learned money the hard way so you don't have to.",
        socialLinks: { twitter: "https://twitter.com/jordanmoney", linkedin: "https://linkedin.com/in/jordanmartinez" },
    },
    {
        id: "2",
        name: "Taylor Kim",
        slug: "taylor-kim",
        avatar: "https://i.pravatar.cc/150?u=taylor",
        bio: "Gen Z money coach on a mission to make investing less scary. Started investing at 19 with $50.",
        socialLinks: { twitter: "https://twitter.com/taylorinvests" },
    },
    {
        id: "3",
        name: "Alex Rivera",
        slug: "alex-rivera",
        avatar: "https://i.pravatar.cc/150?u=alexr",
        bio: "Certified Financial Planner focusing on real estate and tax strategies.",
        socialLinks: { linkedin: "https://linkedin.com/in/arivera" },
    }
];

export const mockCategories: Category[] = [
    { id: "1", name: "Legal Finance", slug: "legal-finance", description: "The financial impact of major legal events. Protecting your wealth during divorces, accidents, estate planning, and contracts." },
    { id: "2", name: "Insurance & Protection", slug: "insurance-and-protection", description: "Risk management strategies for the new generation. Life, health, auto, and property insurance as the foundation of a secure portfolio." },
    { id: "3", name: "Auto & Transport", slug: "auto-and-transport", description: "Analyzing vehicle purchases, maintenance, and financing from a strictly financial perspective." },
    { id: "4", name: "Real Estate & Mortgages", slug: "real-estate-and-mortgages", description: "Your guide to navigating the real estate market. Mortgage tactics, interest rates, and home improvement ROI." },
    { id: "5", name: "Taxes", slug: "taxes", description: "Practical strategies to optimize your tax filing and stop leaving money on the table." },
    { id: "6", name: "Investing & Wealth", slug: "investing-and-wealth", description: "From basics to advanced wealth building. Retirement concepts, 2026 trends, and active cash management strategies." },
    { id: "7", name: "Budgeting & Debt", slug: "budgeting-and-debt", description: "The psychology of everyday money. Smart spending, crushing credit card debt, and guilt-free budgeting." },
    { id: "8", name: "Side Hustles & Fintech", slug: "side-hustles-and-fintech", description: "How to use technology to earn and manage more money. Lucrative side businesses, gig economy, and AI-powered finance apps." },
];

export const mockArticles: Article[] = [
    // --- LEGAL FINANCE ---
    {
        id: "lf-1",
        title: "How a Divorce Can Wreck Your Retirement Plan",
        slug: "divorce-retirement-plan-impact",
        excerpt: "The financial devastation of splitting assets at 50. What every couple should plan for before it is too late.",
        content: `<h2>The Hidden Cost of Divorce</h2><p>Beyond emotional toll, divorce can slash your retirement savings in half. QDROs, alimony, and asset division can derail decades of planning. Here is how to protect yourself.</p>`,
        coverImage: "https://picsum.photos/seed/lf1/800/600",
        publishedAt: "2024-02-22T10:00:00Z",
        author: mockAuthors[2],
        category: mockCategories[0],
        readingTime: 7,
        featured: true,
        articleType: "story",
        keyTakeaways: ["QDROs split retirement accounts in divorce", "Prenups protect more than you think", "Consult a CDFA (Certified Divorce Financial Analyst)"],
        relatedTool: { name: "Freedom Fund Calculator", slug: "freedom-fund-calculator" },
    },
    {
        id: "lf-2",
        title: "Estate Planning Basics: Wills, Trusts, and Power of Attorney",
        slug: "estate-planning-basics",
        excerpt: "Most Americans die without a will. Here is why that is a financial disaster for your family.",
        content: `<h2>Plan Now or Pay Later</h2><p>Without a will, state law decides who gets your assets. A revocable living trust can help you avoid probate and maintain control even after incapacitation.</p>`,
        coverImage: "https://picsum.photos/seed/lf2/800/600",
        publishedAt: "2024-02-19T10:00:00Z",
        author: mockAuthors[0],
        category: mockCategories[0],
        readingTime: 8,
        featured: false,
        articleType: "guide",
        keyTakeaways: ["A will is the minimum, a trust is better", "Power of attorney covers you while alive", "Review estate plans every 3-5 years"],
        relatedTool: { name: "Freedom Fund Calculator", slug: "freedom-fund-calculator" },
    },
    {
        id: "lf-3",
        title: "What to Do Financially After a Car Accident",
        slug: "financial-steps-after-car-accident",
        excerpt: "The first 72 hours after an accident can make or break your financial outcome. Follow this checklist.",
        content: `<h2>Protect Your Finances First</h2><p>Medical bills, insurance claims, and potential lawsuits can spiral. Knowing your rights and documenting everything from minute one can save you thousands.</p>`,
        coverImage: "https://picsum.photos/seed/lf3/800/600",
        publishedAt: "2024-02-15T10:00:00Z",
        author: mockAuthors[1],
        category: mockCategories[0],
        readingTime: 5,
        featured: false,
        articleType: "guide",
        keyTakeaways: ["Document everything immediately", "Do not accept the first settlement offer", "Personal injury attorneys work on contingency"],
        relatedTool: { name: "Freedom Fund Calculator", slug: "freedom-fund-calculator" },
    },
    {
        id: "lf-4",
        title: "How Non-Compete Clauses Affect Your Earning Power",
        slug: "non-compete-clauses-earning-power",
        excerpt: "That clause you signed could cost you your next job. Here is what the FTC ban means for your career.",
        content: `<h2>Breaking Free</h2><p>Non-compete clauses have historically limited workers' ability to negotiate higher salaries or switch jobs. New federal rules are changing the landscape.</p>`,
        coverImage: "https://picsum.photos/seed/lf4/800/600",
        publishedAt: "2024-02-10T10:00:00Z",
        author: mockAuthors[0],
        category: mockCategories[0],
        readingTime: 6,
        featured: false,
        articleType: "news",
        keyTakeaways: ["FTC proposed banning most non-competes", "Existing contracts may be voided", "Consult an employment attorney"],
    },
    {
        id: "lf-5",
        title: "Prenuptial Agreements: Not Just for the Rich",
        slug: "prenuptial-agreements-guide",
        excerpt: "A prenup is not about distrust. It is about financial transparency and protecting both partners.",
        content: `<h2>Modern Prenups</h2><p>Today's prenuptial agreements cover debt protection, business ownership, and even social media clauses. They are financial planning tools, not divorce preparations.</p>`,
        coverImage: "https://picsum.photos/seed/lf5/800/600",
        publishedAt: "2024-02-05T10:00:00Z",
        author: mockAuthors[1],
        category: mockCategories[0],
        readingTime: 5,
        featured: false,
        articleType: "guide",
        keyTakeaways: ["Protects both parties' assets", "Must be signed well before the wedding", "Each party needs their own attorney"],
    },
    {
        id: "lf-6",
        title: "Understanding Power of Attorney: Financial vs Healthcare",
        slug: "power-of-attorney-types",
        excerpt: "Two documents that everyone over 18 needs. Here is the difference and why waiting can be costly.",
        content: `<h2>Two Critical Documents</h2><p>A financial POA handles money decisions if you are incapacitated. A healthcare POA makes medical decisions. Without them, your family faces expensive court proceedings.</p>`,
        coverImage: "https://picsum.photos/seed/lf6/800/600",
        publishedAt: "2024-01-28T10:00:00Z",
        author: mockAuthors[2],
        category: mockCategories[0],
        readingTime: 4,
        featured: false,
        articleType: "guide",
        keyTakeaways: ["Everyone over 18 needs both POAs", "Springing vs immediate POA", "Review and update every 3-5 years"],
    },

    // --- INSURANCE & PROTECTION ---
    {
        id: "ins-1",
        title: "Life Insurance in Your 20s: Why It Is Cheaper Than Your Netflix",
        slug: "life-insurance-in-your-20s",
        excerpt: "The younger you buy, the less you pay. Term life insurance at 25 can cost less than a streaming subscription.",
        content: `<h2>Lock In Low Rates Early</h2><p>A healthy 25-year-old can get a $500K term life policy for under $20/month. Waiting until 40 can triple that cost — or worse, a health event could make you uninsurable.</p>`,
        coverImage: "https://picsum.photos/seed/ins1/800/600",
        publishedAt: "2024-02-21T10:00:00Z",
        author: mockAuthors[1],
        category: mockCategories[1],
        readingTime: 5,
        featured: true,
        articleType: "guide",
        keyTakeaways: ["Term life is affordable for young adults", "Coverage of 10-15x your income is recommended", "Employer life insurance usually is not enough"],
    },
    {
        id: "ins-2",
        title: "Umbrella Insurance: The Most Underrated Protection",
        slug: "umbrella-insurance-explained",
        excerpt: "One lawsuit could wipe you out. For $200-400/year, umbrella insurance adds $1M+ in liability coverage.",
        content: `<h2>Your Safety Net Has a Safety Net</h2><p>Umbrella policies kick in when your auto or homeowners liability limits are exceeded. For anyone with assets to protect, it is one of the best values in insurance.</p>`,
        coverImage: "https://picsum.photos/seed/ins2/800/600",
        publishedAt: "2024-02-13T10:00:00Z",
        author: mockAuthors[2],
        category: mockCategories[1],
        readingTime: 6,
        featured: false,
        articleType: "guide",
        keyTakeaways: ["Covers beyond auto and home limits", "Protects against lawsuits and large claims", "Essential once your net worth exceeds $500K"],
    },
    {
        id: "ins-3",
        title: "Health Insurance Marketplace: How to Actually Save Money",
        slug: "health-insurance-marketplace-savings",
        excerpt: "Open enrollment confusion? Here is how to navigate subsidies, HSAs, and plan tiers to maximize your savings.",
        content: `<h2>Decoding the Marketplace</h2><p>Premium tax credits can reduce your monthly cost significantly. Pairing a high-deductible plan with an HSA creates a triple-tax-advantaged savings vehicle.</p>`,
        coverImage: "https://picsum.photos/seed/ins3/800/600",
        publishedAt: "2024-02-07T10:00:00Z",
        author: mockAuthors[0],
        category: mockCategories[1],
        readingTime: 7,
        featured: false,
        articleType: "guide",
        keyTakeaways: ["Check if you qualify for subsidies", "HSAs offer triple tax benefits", "Bronze plans are not always the cheapest option"],
    },

    {
        id: "ins-4",
        title: "Renters Insurance: The $15/Month Safety Net You Are Ignoring",
        slug: "renters-insurance-guide",
        excerpt: "Your landlord's policy does not cover your stuff. A single theft or fire could cost you everything.",
        content: `<h2>Protect What You Own</h2><p>The average renter owns $20K-$30K in personal property. Renters insurance covers theft, fire, and liability for less than the cost of a streaming service.</p>`,
        coverImage: "https://picsum.photos/seed/ins4/800/600",
        publishedAt: "2024-02-03T10:00:00Z",
        author: mockAuthors[1],
        category: mockCategories[1],
        readingTime: 4,
        featured: false,
        articleType: "guide",
        keyTakeaways: ["Covers personal property and liability", "Costs $10-$20/month on average", "Required by many landlords anyway"],
    },
    {
        id: "ins-5",
        title: "How to File an Insurance Claim Without Getting Lowballed",
        slug: "insurance-claim-tips",
        excerpt: "Adjusters are trained to minimize payouts. Here is how to document and negotiate for what you deserve.",
        content: `<h2>Fight for Full Value</h2><p>Insurance companies are businesses first. Understanding the claims process, documenting everything with photos and receipts, and knowing when to push back can double your payout.</p>`,
        coverImage: "https://picsum.photos/seed/ins5/800/600",
        publishedAt: "2024-01-30T10:00:00Z",
        author: mockAuthors[2],
        category: mockCategories[1],
        readingTime: 7,
        featured: false,
        articleType: "guide",
        keyTakeaways: ["Document everything with photos", "Get independent repair estimates", "You can dispute adjuster valuations"],
    },
    {
        id: "ins-6",
        title: "Disability Insurance: Protecting Your #1 Asset",
        slug: "disability-insurance-explained",
        excerpt: "Your ability to earn is worth millions over your career. Disability insurance is how you protect it.",
        content: `<h2>Your Income Is Your Biggest Asset</h2><p>One in four workers will become disabled before retirement. Short-term and long-term disability policies replace 60-70% of your income if you cannot work.</p>`,
        coverImage: "https://picsum.photos/seed/ins6/800/600",
        publishedAt: "2024-01-25T10:00:00Z",
        author: mockAuthors[0],
        category: mockCategories[1],
        readingTime: 6,
        featured: false,
        articleType: "guide",
        keyTakeaways: ["One in four workers become disabled", "Own-occupation policies are superior", "Employer coverage alone is often insufficient"],
    },

    // --- AUTO & TRANSPORT ---
    {
        id: "auto-1",
        title: "Leasing vs Buying a Car: The Real Math in 2026",
        slug: "leasing-vs-buying-car-2026",
        excerpt: "Everyone has an opinion, but few have done the math. We break down the true cost of ownership vs leasing.",
        content: `<h2>Total Cost of Ownership</h2><p>Buying wins in the long run if you keep the car 7+ years. But leasing can be smarter for business owners who deduct payments and always want the latest safety tech.</p>`,
        coverImage: "https://picsum.photos/seed/auto1/800/600",
        publishedAt: "2024-02-20T10:00:00Z",
        author: mockAuthors[0],
        category: mockCategories[2],
        readingTime: 7,
        featured: true,
        articleType: "guide",
        keyTakeaways: ["Buying saves money over 7+ years", "Leasing has tax advantages for businesses", "Factor in maintenance, insurance, and depreciation"],
    },
    {
        id: "auto-2",
        title: "EV Tax Credits in 2026: Which Cars Qualify?",
        slug: "ev-tax-credits-2026",
        excerpt: "The clean vehicle credit can save you up to $7,500, but the eligibility rules are confusing. We simplify them.",
        content: `<h2>Navigating the EV Credit Maze</h2><p>Not all EVs qualify. Manufacturing origin, MSRP caps, and income limits determine your eligibility. Used EVs now qualify for up to $4,000.</p>`,
        coverImage: "https://picsum.photos/seed/auto2/800/600",
        publishedAt: "2024-02-14T10:00:00Z",
        author: mockAuthors[2],
        category: mockCategories[2],
        readingTime: 6,
        featured: false,
        articleType: "news",
        keyTakeaways: ["New EVs can get up to $7,500 credit", "Used EVs qualify for up to $4,000", "Check IRS fueleconomy.gov for eligible models"],
    },
    {
        id: "auto-3",
        title: "How to Get the Best Auto Loan Rate (Even With Average Credit)",
        slug: "best-auto-loan-rate-tips",
        excerpt: "Dealer financing is not always the best deal. Here is how to shop for rates and save thousands over the loan term.",
        content: `<h2>Shop Before You Buy</h2><p>Getting pre-approved by a credit union or online lender before visiting the dealership gives you leverage. Even a 1% lower rate on a $30K loan saves over $900.</p>`,
        coverImage: "https://picsum.photos/seed/auto3/800/600",
        publishedAt: "2024-02-08T10:00:00Z",
        author: mockAuthors[1],
        category: mockCategories[2],
        readingTime: 5,
        featured: false,
        articleType: "guide",
        keyTakeaways: ["Get pre-approved before visiting dealers", "Credit unions often have the best rates", "Shorter loan terms save thousands in interest"],
    },

    {
        id: "auto-4",
        title: "The True Cost of Car Ownership in 2026",
        slug: "true-cost-car-ownership-2026",
        excerpt: "Gas, insurance, maintenance, depreciation... the sticker price is just the beginning.",
        content: `<h2>Beyond the Monthly Payment</h2><p>AAA estimates the average car costs over $12,000/year to own and operate. Here is how to calculate your real cost per mile and decide if ownership still makes sense.</p>`,
        coverImage: "https://picsum.photos/seed/auto4/800/600",
        publishedAt: "2024-02-04T10:00:00Z",
        author: mockAuthors[2],
        category: mockCategories[2],
        readingTime: 6,
        featured: false,
        articleType: "guide",
        keyTakeaways: ["Average ownership cost exceeds $12K/year", "Depreciation is the biggest hidden cost", "Calculate cost-per-mile for true comparison"],
    },
    {
        id: "auto-5",
        title: "How to Negotiate a Car Price Like a Pro",
        slug: "negotiate-car-price",
        excerpt: "Dealers make thousands on uninformed buyers. Use these tactics to pay invoice price or below.",
        content: `<h2>Knowledge Is Leverage</h2><p>Knowing the dealer invoice price, timing your purchase at month-end, and being willing to walk away are the three most powerful negotiation tools.</p>`,
        coverImage: "https://picsum.photos/seed/auto5/800/600",
        publishedAt: "2024-01-30T10:00:00Z",
        author: mockAuthors[0],
        category: mockCategories[2],
        readingTime: 5,
        featured: false,
        articleType: "guide",
        keyTakeaways: ["Research invoice prices before visiting", "Buy at month or quarter end", "Focus on out-the-door price, not monthly payment"],
    },
    {
        id: "auto-6",
        title: "Is Gap Insurance Worth It? A Financial Analysis",
        slug: "gap-insurance-analysis",
        excerpt: "If your car is totaled, your insurance pays what it is worth, not what you owe. That gap can be devastating.",
        content: `<h2>Mind the Gap</h2><p>New cars lose 20% of their value in year one. If you financed with a small down payment, you could owe more than the car is worth for years. Gap insurance covers the difference.</p>`,
        coverImage: "https://picsum.photos/seed/auto6/800/600",
        publishedAt: "2024-01-27T10:00:00Z",
        author: mockAuthors[1],
        category: mockCategories[2],
        readingTime: 4,
        featured: false,
        articleType: "guide",
        keyTakeaways: ["Essential for low down payment loans", "Buy from your insurer, not the dealer", "Unnecessary once loan balance equals car value"],
    },

    // --- REAL ESTATE & MORTGAGES ---
    {
        id: "re-1",
        title: "The Psychology of the 5.9% Mortgage Rate Threshold",
        slug: "mortgage-rate-threshold-psychology",
        excerpt: "Why homebuyer demand skyrockets when rates dip below 6%, and what it means for your home search.",
        content: `<h2>The Magic Number</h2><p>Historically, the 6% mark acts as a psychological barrier for homebuyers. When rates dip into the 5s, sidelined buyers flood back into the market, driving up competition and prices.</p>`,
        coverImage: "https://picsum.photos/seed/mock10/800/600",
        publishedAt: "2024-02-16T10:00:00Z",
        author: mockAuthors[2],
        category: mockCategories[3],
        readingTime: 5,
        featured: true,
        articleType: "story",
        keyTakeaways: ["Rates below 6% trigger bidding wars", "Buying slightly higher rates with less competition can sometimes be cheaper", "You can date the rate but you marry the price"],
        relatedTool: { name: "Savings Goal Calculator", slug: "savings-goal-calculator" },
    },
    {
        id: "re-2",
        title: "Best Down Payment Assistance Programs by State",
        slug: "down-payment-assistance-programs",
        excerpt: "First-time homebuyer? You might be leaving thousands of dollars of free grant money on the table.",
        content: `<h2>Free Money for Homebuyers</h2><p>Many states and municipalities offer grants or forgivable loans to help cover down payments and closing costs for eligible first-time buyers.</p>`,
        coverImage: "https://picsum.photos/seed/mock11/800/600",
        publishedAt: "2024-02-09T10:00:00Z",
        author: mockAuthors[0],
        category: mockCategories[3],
        readingTime: 12,
        featured: false,
        articleType: "guide",
        keyTakeaways: ["Programs often have income limits", "Some grants do not need to be repaid if you stay 5+ years", "Always check local housing authority websites"],
        relatedTool: { name: "Savings Goal Calculator", slug: "savings-goal-calculator" },
    },
    {
        id: "re-3",
        title: "Climate-Resilient Home Features With Best ROI",
        slug: "climate-resilient-home-features-roi",
        excerpt: "As extreme weather increases, certain home upgrades are paying off big in resale value and insurance savings.",
        content: `<h2>Future-Proofing Your Home</h2><p>Upgrades like impact-resistant roofs, French drains, and solar-plus-battery systems not only protect your home but significantly lower insurance premiums.</p>`,
        coverImage: "https://picsum.photos/seed/mock12/800/600",
        publishedAt: "2024-02-04T10:00:00Z",
        author: mockAuthors[1],
        category: mockCategories[3],
        readingTime: 6,
        featured: false,
        articleType: "guide",
        keyTakeaways: ["Insurance savings offset upgrade costs over time", "Elevating HVAC units prevents flood damage", "Energy independence adds huge resale value"],
        relatedTool: { name: "Savings Goal Calculator", slug: "savings-goal-calculator" },
    },

    {
        id: "re-4",
        title: "How to Win a Bidding War Without Overpaying",
        slug: "win-bidding-war-strategies",
        excerpt: "Competing against cash offers? These tactics make your financed offer stand out to sellers.",
        content: `<h2>Stand Out in a Crowd</h2><p>Escalation clauses, appraisal gap coverage, and flexible closing dates can make your offer more attractive than a higher competing bid.</p>`,
        coverImage: "https://picsum.photos/seed/re4/800/600",
        publishedAt: "2024-02-01T10:00:00Z",
        author: mockAuthors[0],
        category: mockCategories[3],
        readingTime: 6,
        featured: false,
        articleType: "guide",
        keyTakeaways: ["Escalation clauses automate competitive bidding", "Personal letters to sellers still work", "Waiving inspection is risky but common"],
    },
    {
        id: "re-5",
        title: "House Hacking: Live for Free With Rental Income",
        slug: "house-hacking-strategy",
        excerpt: "Buy a duplex, live in one unit, rent the other. Your tenant pays your mortgage.",
        content: `<h2>The Ultimate First Purchase</h2><p>House hacking lets you qualify for owner-occupied financing (lower rates) while building equity with rental income. It is the most accessible path to real estate investing.</p>`,
        coverImage: "https://picsum.photos/seed/re5/800/600",
        publishedAt: "2024-01-28T10:00:00Z",
        author: mockAuthors[1],
        category: mockCategories[3],
        readingTime: 7,
        featured: false,
        articleType: "guide",
        keyTakeaways: ["FHA loans allow 3.5% down on multi-family", "Rental income counts toward qualification", "Start building a portfolio while living for free"],
    },
    {
        id: "re-6",
        title: "Refinancing in 2026: When Does It Actually Make Sense?",
        slug: "refinancing-guide-2026",
        excerpt: "The 1% rule is outdated. Here is the modern framework for deciding if a refinance saves you money.",
        content: `<h2>Run the Numbers</h2><p>Factor in closing costs, how long you plan to stay, and your break-even point. Sometimes a no-closing-cost refi at a slightly higher rate is the smarter play.</p>`,
        coverImage: "https://picsum.photos/seed/re6/800/600",
        publishedAt: "2024-01-25T10:00:00Z",
        author: mockAuthors[2],
        category: mockCategories[3],
        readingTime: 5,
        featured: false,
        articleType: "guide",
        keyTakeaways: ["Calculate break-even in months, not percentages", "No-closing-cost options exist", "Cash-out refis can consolidate high-interest debt"],
    },

    // --- TAXES ---
    {
        id: "tax-1",
        title: "Itemizing State and Local Taxes Under the New $40,400 Cap",
        slug: "itemizing-salt-taxes",
        excerpt: "A deep dive into the recent changes to SALT deductions and how high-earners in high-tax states can navigate them.",
        content: `<h2>The SALT Cap Shift</h2><p>With legislative changes altering the State and Local Tax deduction caps, taxpayers in states like NY, NJ, and CA need new strategies to minimize their federal tax burden.</p>`,
        coverImage: "https://picsum.photos/seed/mock13/800/600",
        publishedAt: "2024-02-20T10:00:00Z",
        author: mockAuthors[2],
        category: mockCategories[4],
        readingTime: 7,
        featured: true,
        articleType: "news",
        keyTakeaways: ["The SALT cap affects high-tax state residents", "Workarounds exist for business owners", "Consult a CPA to navigate the exact phase-outs"],
        relatedTool: { name: "Freedom Fund Calculator", slug: "freedom-fund-calculator" },
    },
    {
        id: "tax-2",
        title: "W-4 Adjustment Guide: Stop Giving the IRS a Free Loan",
        slug: "w4-adjustment-guide",
        excerpt: "If you always get a huge tax refund, you are doing it wrong. Learn how to adjust your withholdings for bigger paychecks.",
        content: `<h2>The Refund Myth</h2><p>A big tax refund isn't a bonus from the government. It's your own money that you let the IRS hold interest-free for a year. Adjusting your W-4 puts that money back in your monthly paycheck.</p>`,
        coverImage: "https://picsum.photos/seed/mock14/800/600",
        publishedAt: "2024-01-25T10:00:00Z",
        author: mockAuthors[0],
        category: mockCategories[4],
        readingTime: 5,
        featured: false,
        articleType: "guide",
        keyTakeaways: ["Aim for a refund close to $0", "Use the IRS withholding calculator", "Update your W-4 after major life events"],
        relatedTool: { name: "Freedom Fund Calculator", slug: "freedom-fund-calculator" },
    },
    {
        id: "tax-3",
        title: "Qualified Overtime Tax Deduction Rules (OBBBA)",
        slug: "qualified-overtime-tax-deduction",
        excerpt: "Understanding the new overtime tax exemptions and how to ensure your extra hours aren't eaten by taxes.",
        content: `<h2>Keeping What You Earn</h2><p>Recent legislation changes how consecutive overtime hours are taxed. Ensure your employer is correctly classifying these hours to maximize your take-home pay.</p>`,
        coverImage: "https://picsum.photos/seed/mock15/800/600",
        publishedAt: "2024-02-02T10:00:00Z",
        author: mockAuthors[2],
        category: mockCategories[4],
        readingTime: 6,
        featured: false,
        articleType: "news",
        keyTakeaways: ["Overtime tax rules are shifting", "Review your paystubs carefully", "Tipped workers have specific new exemptions"],
        relatedTool: { name: "Freedom Fund Calculator", slug: "freedom-fund-calculator" },
    },

    {
        id: "tax-4",
        title: "Freelancer Tax Deductions You Are Probably Missing",
        slug: "freelancer-tax-deductions",
        excerpt: "Home office, mileage, software subscriptions... self-employed workers leave thousands on the table.",
        content: `<h2>Deduct Everything Legal</h2><p>As an independent contractor, you can deduct business expenses that W-2 employees cannot. The key is meticulous record-keeping and understanding which expenses qualify.</p>`,
        coverImage: "https://picsum.photos/seed/tax4/800/600",
        publishedAt: "2024-01-28T10:00:00Z",
        author: mockAuthors[0],
        category: mockCategories[4],
        readingTime: 8,
        featured: false,
        articleType: "guide",
        keyTakeaways: ["Home office deduction has two methods", "Track mileage with an app", "Retirement contributions reduce self-employment tax"],
        relatedTool: { name: "Freedom Fund Calculator", slug: "freedom-fund-calculator" },
    },
    {
        id: "tax-5",
        title: "Standard Deduction vs Itemizing: 2026 Comparison",
        slug: "standard-deduction-vs-itemizing-2026",
        excerpt: "The standard deduction keeps rising. Here is how to know if itemizing still saves you money.",
        content: `<h2>The Tipping Point</h2><p>With the 2026 standard deduction at $15,000 for single filers, you need significant mortgage interest, SALT, and charitable contributions to benefit from itemizing.</p>`,
        coverImage: "https://picsum.photos/seed/tax5/800/600",
        publishedAt: "2024-01-22T10:00:00Z",
        author: mockAuthors[1],
        category: mockCategories[4],
        readingTime: 5,
        featured: false,
        articleType: "guide",
        keyTakeaways: ["Most filers benefit from the standard deduction", "Bunching deductions can make itemizing worthwhile", "Charitable donor-advised funds help bunch"],
        relatedTool: { name: "Freedom Fund Calculator", slug: "freedom-fund-calculator" },
    },
    {
        id: "tax-6",
        title: "Capital Gains Tax: Short-Term vs Long-Term Rates",
        slug: "capital-gains-tax-rates",
        excerpt: "Selling investments too early can double your tax bill. Timing your sales strategically saves thousands.",
        content: `<h2>Patience Pays Off</h2><p>Short-term capital gains are taxed as ordinary income (up to 37%). Long-term gains (held 1+ year) max out at 20%. Tax-loss harvesting can offset gains entirely.</p>`,
        coverImage: "https://picsum.photos/seed/tax6/800/600",
        publishedAt: "2024-01-18T10:00:00Z",
        author: mockAuthors[2],
        category: mockCategories[4],
        readingTime: 6,
        featured: false,
        articleType: "guide",
        keyTakeaways: ["Hold investments 1+ year for lower rates", "Tax-loss harvesting offsets gains", "$3,000 annual loss deduction against income"],
        relatedTool: { name: "Freedom Fund Calculator", slug: "freedom-fund-calculator" },
    },

    // --- INVESTING & WEALTH ---
    {
        id: "inv-1",
        title: "Roth IRA vs Traditional IRA Explained in Simple English",
        slug: "roth-ira-vs-traditional-ira",
        excerpt: "Taxes now or taxes later? We break down exactly which retirement account makes the most sense for your current salary.",
        content: `<h2>The Great Tax Debate</h2><p>A Traditional IRA gives you a tax break today. A Roth IRA gives you tax-free money in retirement. Which is better? It depends on your current tax bracket vs your expected future tax bracket.</p>`,
        coverImage: "https://picsum.photos/seed/mock4/800/600",
        publishedAt: "2024-02-14T10:00:00Z",
        author: mockAuthors[2],
        category: mockCategories[5],
        readingTime: 7,
        featured: true,
        articleType: "guide",
        keyTakeaways: ["Roth = pay taxes now", "Traditional = pay taxes later", "Young earners usually benefit more from a Roth"],
        relatedTool: { name: "Wealth Growth Simulator", slug: "wealth-growth-simulator" },
    },
    {
        id: "inv-2",
        title: "How to Start Investing with Little Money",
        slug: "start-investing-little-money",
        excerpt: "You don't need thousands to start. Here is how to begin your investing journey with just $50.",
        content: `<h2>Fractional Shares are Your Best Friend</h2><p>Gone are the days of needing $3,000 to open a mutual fund. Today, you can buy pieces of companies for as little as $1.</p>`,
        coverImage: "https://picsum.photos/seed/mock5/800/600",
        publishedAt: "2024-02-08T10:00:00Z",
        author: mockAuthors[1],
        category: mockCategories[5],
        readingTime: 5,
        featured: false,
        articleType: "guide",
        keyTakeaways: ["Use zero-fee brokerages", "Buy fractional shares of index funds", "Automate your investments"],
        relatedTool: { name: "Wealth Growth Simulator", slug: "wealth-growth-simulator" },
    },
    {
        id: "inv-3",
        title: "Active Cash Management: Bond Ladders vs CDs",
        slug: "bond-ladders-vs-cds",
        excerpt: "Stop leaving large cash balances in standard savings. Here is how to actively manage your liquid net worth.",
        content: `<h2>Maximizing Yield on Cash</h2><p>When interest rates are high, leaving money in a 0.01% checking account is a mistake. Consider building a Treasury bill ladder or using staggered certificates of deposit to lock in yields.</p>`,
        coverImage: "https://picsum.photos/seed/mock7/800/600",
        publishedAt: "2024-02-18T10:00:00Z",
        author: mockAuthors[2],
        category: mockCategories[5],
        readingTime: 8,
        featured: false,
        articleType: "guide",
        keyTakeaways: ["T-bills often beat CDs and are state-tax exempt", "Ladders provide liquidity and yield", "Match durations to your cash flow needs"],
        relatedTool: { name: "Wealth Growth Simulator", slug: "wealth-growth-simulator" },
    },
    {
        id: "inv-4",
        title: "Child Accounts vs 529 Plans: What Parents Need to Know",
        slug: "child-accounts-vs-529-plans",
        excerpt: "Saving for your kid's future? Understand the tax implications and flexibility of different account types.",
        content: `<h2>Education vs Flexibility</h2><p>A 529 plan offers great tax benefits if the money is used for education. But what if they don't go to college? A custodial UTMA/UGMA account might offer more flexibility.</p>`,
        coverImage: "https://picsum.photos/seed/mock6/800/600",
        publishedAt: "2024-02-01T10:00:00Z",
        author: mockAuthors[2],
        category: mockCategories[5],
        readingTime: 6,
        featured: false,
        articleType: "guide",
        keyTakeaways: ["529s are highly tax-advantaged for education", "Custodial accounts offer maximum flexibility", "New rules allow rolling unused 529 funds into a Roth IRA"],
        relatedTool: { name: "Savings Goal Calculator", slug: "savings-goal-calculator" },
    },
    {
        id: "inv-5",
        title: "Investing in Fractional Real Estate in 2026",
        slug: "fractional-real-estate-2026",
        excerpt: "How platforms are dividing commercial and residential properties into tradeable shares, and if it's worth your money.",
        content: `<h2>Real Estate for the Masses</h2><p>Crowdfunding platforms allow you to buy shares of an apartment building or commercial space. But beware of the fees and lack of liquidity.</p>`,
        coverImage: "https://picsum.photos/seed/mock8/800/600",
        publishedAt: "2024-02-10T10:00:00Z",
        author: mockAuthors[1],
        category: mockCategories[5],
        readingTime: 7,
        featured: false,
        articleType: "news",
        keyTakeaways: ["Lower barrier to entry for real estate", "Watch out for platform fees", "Investments are often highly illiquid"],
        relatedTool: { name: "Wealth Growth Simulator", slug: "wealth-growth-simulator" },
    },
    {
        id: "inv-6",
        title: "Tokenized Real-World Assets Explained",
        slug: "tokenized-real-world-assets",
        excerpt: "Blockchain meets traditional finance: how tokenized treasuries and commodities are changing the investing landscape.",
        content: `<h2>Blockchain Bridges the Gap</h2><p>RWA (Real World Assets) tokenization brings traditional financial instruments like bonds and gold onto the blockchain for faster settlement and transparency.</p>`,
        coverImage: "https://picsum.photos/seed/mock9/800/600",
        publishedAt: "2024-02-03T10:00:00Z",
        author: mockAuthors[0],
        category: mockCategories[5],
        readingTime: 6,
        featured: false,
        articleType: "news",
        keyTakeaways: ["Brings 24/7 trading to traditional assets", "Increases transparency via blockchain", "Regulatory landscape is still evolving"],
        relatedTool: { name: "Wealth Growth Simulator", slug: "wealth-growth-simulator" },
    },

    // --- BUDGETING & DEBT ---
    {
        id: "bd-1",
        title: "How to Justify Small Luxuries on a Budget",
        slug: "justify-small-luxuries-budget",
        excerpt: "Budgeting shouldn't mean misery. Here is how to build guilt-free spending into your financial plan.",
        content: `<h2>The Joy of Small Luxuries</h2><p>We often think of budgeting as restriction. But true financial wellness includes allowing yourself small joys without derailing your goals.</p><p>By intentionally setting aside 5-10% of your income for 'fun money', you prevent budget fatigue.</p>`,
        coverImage: "https://picsum.photos/seed/mock1/800/600",
        publishedAt: "2024-02-15T10:00:00Z",
        author: mockAuthors[0],
        category: mockCategories[6],
        readingTime: 4,
        featured: true,
        articleType: "story",
        keyTakeaways: ["Budgeting is about allocation, not restriction", "Set aside 5-10% for guilt-free spending", "Small joys prevent budget burnout"],
        relatedTool: { name: "Debt Payoff Strategist", slug: "debt-payoff-strategist" },
    },
    {
        id: "bd-2",
        title: "Debt Avalanche vs Snowball Method: Which is Faster?",
        slug: "debt-avalanche-vs-snowball",
        excerpt: "Compare the two most popular debt payoff strategies to find out which one saves you the most money.",
        content: `<h2>Avalanche vs Snowball</h2><p>The debt avalanche targets high-interest debt first, saving you money mathematically. The snowball targets small balances first, giving you psychological wins.</p>`,
        coverImage: "https://picsum.photos/seed/mock2/800/600",
        publishedAt: "2024-02-12T10:00:00Z",
        author: mockAuthors[0],
        category: mockCategories[6],
        readingTime: 6,
        featured: false,
        articleType: "guide",
        keyTakeaways: ["Avalanche saves the most money", "Snowball builds momentum faster", "Choose the one you will actually stick to"],
        relatedTool: { name: "Debt Payoff Strategist", slug: "debt-payoff-strategist" },
    },
    {
        id: "bd-3",
        title: "\"Loud Budgeting\" Phrases You Need to Start Using",
        slug: "loud-budgeting-phrases",
        excerpt: "Stop feeling awkward about turning down expensive plans. Use these scripts to protect your peace and your wallet.",
        content: `<h2>What is Loud Budgeting?</h2><p>Loud budgeting is the act of confidently stating your financial boundaries out loud. Instead of making excuses, you simply state your priorities.</p>`,
        coverImage: "https://picsum.photos/seed/mock3/800/600",
        publishedAt: "2024-02-05T10:00:00Z",
        author: mockAuthors[1],
        category: mockCategories[6],
        readingTime: 3,
        featured: false,
        articleType: "guide",
        keyTakeaways: ["Own your financial choices", "True friends respect your boundaries", "A simple 'that's not in my budget' is a complete sentence"],
        relatedTool: { name: "Debt Payoff Strategist", slug: "debt-payoff-strategist" },
    },

    {
        id: "bd-4",
        title: "The 50/30/20 Rule Is Dead. Try This Instead",
        slug: "50-30-20-rule-alternative",
        excerpt: "The classic budgeting framework does not work for most modern incomes. Here is a more flexible approach.",
        content: `<h2>A Better Framework</h2><p>With housing costs exceeding 30% for most Americans, the traditional rule breaks immediately. The 'pay yourself first' method focuses on savings rate, not arbitrary percentages.</p>`,
        coverImage: "https://picsum.photos/seed/bd4/800/600",
        publishedAt: "2024-01-30T10:00:00Z",
        author: mockAuthors[2],
        category: mockCategories[6],
        readingTime: 5,
        featured: false,
        articleType: "guide",
        keyTakeaways: ["Focus on savings rate, not spending categories", "Automate savings before spending", "Adjust percentages to your local cost of living"],
        relatedTool: { name: "Debt Payoff Strategist", slug: "debt-payoff-strategist" },
    },
    {
        id: "bd-5",
        title: "Credit Card Rewards Hacking: Maximize Without Overspending",
        slug: "credit-card-rewards-hacking",
        excerpt: "Earn hundreds in cash back by routing your existing spending through the right cards.",
        content: `<h2>Spend Smarter, Not More</h2><p>The key to credit card rewards is never spending more than you would with cash. Route groceries, gas, and bills through category-specific cards to earn 3-5% back on everything.</p>`,
        coverImage: "https://picsum.photos/seed/bd5/800/600",
        publishedAt: "2024-01-26T10:00:00Z",
        author: mockAuthors[0],
        category: mockCategories[6],
        readingTime: 6,
        featured: false,
        articleType: "guide",
        keyTakeaways: ["Never carry a balance for rewards", "Category cards beat flat-rate cards", "Sign-up bonuses are the biggest wins"],
        relatedTool: { name: "Debt Payoff Strategist", slug: "debt-payoff-strategist" },
    },
    {
        id: "bd-6",
        title: "Emergency Fund: How Much Is Enough in 2026?",
        slug: "emergency-fund-2026",
        excerpt: "Three months? Six months? The right answer depends on your job, health, and risk tolerance.",
        content: `<h2>Your Financial Safety Net</h2><p>Dual-income households with stable jobs may need only 3 months. Freelancers and single-income families should target 6-12 months. Keep it in a high-yield savings account.</p>`,
        coverImage: "https://picsum.photos/seed/bd6/800/600",
        publishedAt: "2024-01-20T10:00:00Z",
        author: mockAuthors[1],
        category: mockCategories[6],
        readingTime: 4,
        featured: false,
        articleType: "guide",
        keyTakeaways: ["3-12 months depending on stability", "High-yield savings accounts earn 4-5% APY", "Start with $1,000 mini emergency fund"],
        relatedTool: { name: "Savings Goal Calculator", slug: "savings-goal-calculator" },
    },

    // --- SIDE HUSTLES & FINTECH ---
    {
        id: "sf-1",
        title: "High-Ticket B2B Side Hustles for 2026",
        slug: "high-ticket-b2b-side-hustles",
        excerpt: "Stop competing for $5 gigs on Fiverr. Here is how to sell high-value services directly to other businesses.",
        content: `<h2>B2B is the Secret Sauce</h2><p>Businesses have budgets; individuals have feelings. By transitioning your skills from B2C to B2B—like offering lead generation or specialized software consulting—you can 10x your hourly rate.</p>`,
        coverImage: "https://picsum.photos/seed/mock19/800/600",
        publishedAt: "2024-02-17T10:00:00Z",
        author: mockAuthors[0],
        category: mockCategories[7],
        readingTime: 7,
        featured: true,
        articleType: "guide",
        keyTakeaways: ["Businesses pay for ROI, not hours", "LinkedIn is your best sales channel", "Specialize in one niche software tool"],
        relatedTool: { name: "Freedom Fund Calculator", slug: "freedom-fund-calculator" },
    },
    {
        id: "sf-2",
        title: "AI Apps That Manage Your Money Automatically",
        slug: "ai-money-management-apps",
        excerpt: "The future is hands-free. We review the top AI tools that invest, save, and negotiate bills for you.",
        content: `<h2>Robo-Advisors on Steroids</h2><p>Modern fintech apps don't just show you graphs; they take action. From identifying useless subscriptions to automatically moving cash between high-yield accounts based on algorithms.</p>`,
        coverImage: "https://picsum.photos/seed/mock16/800/600",
        publishedAt: "2024-02-19T10:00:00Z",
        author: mockAuthors[1],
        category: mockCategories[7],
        readingTime: 6,
        featured: false,
        articleType: "guide",
        keyTakeaways: ["AI can optimize cash sweep accounts", "Automated negotiation works for telecom bills", "Always review the AI's permissions"],
    },
    {
        id: "sf-3",
        title: "How to Start a UGC Business (User Generated Content)",
        slug: "how-to-start-ugc-business",
        excerpt: "You don't need millions of followers to get paid by brands. You just need a smartphone and good lighting.",
        content: `<h2>The Anti-Influencer Model</h2><p>Brands need authentic-looking videos for their TikTok and Instagram ads. They pay neat sums for everyday people to film reviews of their products—no posting to your own feed required.</p>`,
        coverImage: "https://picsum.photos/seed/mock20/800/600",
        publishedAt: "2024-02-13T10:00:00Z",
        author: mockAuthors[1],
        category: mockCategories[7],
        readingTime: 6,
        featured: false,
        articleType: "guide",
        keyTakeaways: ["UGC creators are essentially freelance actors", "Build a portfolio with items you already own", "Pitch directly to mid-sized ecommerce brands"],
        relatedTool: { name: "Freedom Fund Calculator", slug: "freedom-fund-calculator" },
    },
    {
        id: "sf-4",
        title: "Using Passkeys for Financial Apps in 2026",
        slug: "passkeys-financial-apps-2026",
        excerpt: "Passwords are dead. Here is why passkeys are making your banking apps virtually unhackable.",
        content: `<h2>The End of Passwords</h2><p>With major banks finally adopting FIDO passkey standards, the risk of phishing and database leaks is drastically reduced. Here is how to set them up across your portfolio.</p>`,
        coverImage: "https://picsum.photos/seed/mock17/800/600",
        publishedAt: "2024-02-11T10:00:00Z",
        author: mockAuthors[2],
        category: mockCategories[7],
        readingTime: 5,
        featured: false,
        articleType: "guide",
        keyTakeaways: ["Passkeys rely on device biometrics", "They prevent phishing attacks", "Ensure you have a cloud sync backup for device loss"],
    },
    {
        id: "sf-5",
        title: "Selling Digital Printables on Etsy: What Still Works",
        slug: "selling-digital-printables-etsy",
        excerpt: "The market is flooded, but there is still money to be made. Discover the highly-specific niches that are actually selling.",
        content: `<h2>The Riches are in the Niches</h2><p>Generic planners don't sell anymore. But specialized forms for niche industries (like 'Dog Walker Intake Forms' or 'Wedding Florist Checklists') sell consistently with zero inventory costs.</p>`,
        coverImage: "https://picsum.photos/seed/mock21/800/600",
        publishedAt: "2024-02-07T10:00:00Z",
        author: mockAuthors[0],
        category: mockCategories[7],
        readingTime: 5,
        featured: false,
        articleType: "guide",
        keyTakeaways: ["Solve a specific problem for a specific profession", "Use SEO optimized titles and tags", "Bundle items to increase average order value"],
        relatedTool: { name: "Freedom Fund Calculator", slug: "freedom-fund-calculator" },
    },
    {
        id: "sf-6",
        title: "SoFi vs Discover for Debt Consolidation",
        slug: "sofi-vs-discover-debt-consolidation",
        excerpt: "An in-depth comparison of the two giants in personal loans. Which app offers better rates and user experience?",
        content: `<h2>Refinancing Made Easy</h2><p>Both SoFi and Discover offer competitive personal loans for consolidating high-interest credit card debt. But their approval algorithms and fee structures differ wildly.</p>`,
        coverImage: "https://picsum.photos/seed/mock18/800/600",
        publishedAt: "2024-02-06T10:00:00Z",
        author: mockAuthors[0],
        category: mockCategories[7],
        readingTime: 8,
        featured: false,
        articleType: "guide",
        keyTakeaways: ["SoFi offers unemployment protection features", "Discover shines in customer service", "Always check pre-qualification rates first"],
    },
];

export class MockCMSAdapter implements CMSAdapter {
    async getFeaturedArticle(): Promise<Article | null> {
        await new Promise(resolve => setTimeout(resolve, 600));
        return mockArticles.find((a) => a.featured) || mockArticles[0];
    }

    async getHeroArticles(limit: number): Promise<Article[]> {
        await new Promise(resolve => setTimeout(resolve, 400));
        return mockArticles.slice(0, limit);
    }

    async getCuratedArticles(): Promise<Article[]> {
        await new Promise(resolve => setTimeout(resolve, 400));
        return mockArticles.slice(1, 4);
    }

    async getLatestArticles({ page, limit }: { page: number; limit: number }): Promise<Article[]> {
        await new Promise(resolve => setTimeout(resolve, 500));
        const start = (page - 1) * limit;
        return mockArticles.slice(start, start + limit);
    }

    async getArticleBySlug(slug: string): Promise<Article | null> {
        await new Promise(resolve => setTimeout(resolve, 300));
        return mockArticles.find((a) => a.slug === slug) || null;
    }

    async getArticlesByCategory(categorySlug: string, { page, limit }: { page: number; limit: number }): Promise<{ articles: Article[]; totalPages: number }> {
        await new Promise(resolve => setTimeout(resolve, 400));
        const filtered = mockArticles.filter((a) => a.category.slug === categorySlug);
        const totalPages = Math.ceil(filtered.length / limit);
        const start = (page - 1) * limit;
        return {
            articles: filtered.slice(start, start + limit),
            totalPages
        };
    }

    async getArticlesByCategorySlugs(slugs: string[], limit: number): Promise<Record<string, Article[]>> {
        await new Promise(resolve => setTimeout(resolve, 800));
        const result: Record<string, Article[]> = {};
        for (const slug of slugs) {
            result[slug] = mockArticles.filter(a => a.category.slug === slug).slice(0, limit);
        }
        return result;
    }

    async getAllCategories(): Promise<Category[]> {
        await new Promise(resolve => setTimeout(resolve, 200));
        return mockCategories;
    }

    async getRelatedArticles(currentArticleId: string): Promise<Article[]> {
        await new Promise(resolve => setTimeout(resolve, 300));
        return mockArticles.filter((a) => a.id !== currentArticleId).slice(0, 3);
    }

    async searchArticles(query: string): Promise<Article[]> {
        await new Promise(resolve => setTimeout(resolve, 400));
        const lowerQuery = query.toLowerCase();
        return mockArticles.filter(article =>
            article.title.toLowerCase().includes(lowerQuery) ||
            article.excerpt.toLowerCase().includes(lowerQuery) ||
            article.content.toLowerCase().includes(lowerQuery)
        );
    }

    async getPillarArticles(): Promise<Article[]> {
        await new Promise(resolve => setTimeout(resolve, 400));
        // Mock: return the first (featured) article from each category
        const seen = new Set<string>();
        return mockArticles.filter(a => {
            if (seen.has(a.category.slug)) return false;
            seen.add(a.category.slug);
            return true;
        });
    }

    async getSiblingSpokes(_parentPillarSlug: string, currentArticleSlug: string, limit: number): Promise<Article[]> {
        await new Promise(resolve => setTimeout(resolve, 300));
        // Mock: no spoke_meta in mock data, return empty
        return mockArticles.filter(a => a.slug !== currentArticleSlug).slice(0, limit);
    }

    async getAllSlugs(): Promise<Set<string>> {
        return new Set(mockArticles.map(a => a.slug));
    }
}

export const cms = new MockCMSAdapter();
